# Generated by Django 5.1.4 on 2024-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_delete_product_rename_product_cartitem_coffee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
